In [1]:
# Experiment no.6

In [2]:
#Aim: To perform operation of sampling and population

In [3]:
# Name: Aditi
# Roll no: 20
# Sec: C
# Subject: DSS
# Date: 06/08/2026

In [4]:
#importing the basic library
import pandas as pd

In [5]:
import os

In [6]:
os.getcwd()

'C:\\Users\\user'

In [7]:
os.chdir('C:\\Users\\user')

In [9]:
data=pd.read_csv("C:\\Users\\user\\OneDrive\\Desktop\\heart - Copy.csv")

In [12]:
data.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0

In [14]:
#Filter records where age is greater than 60
age_above_60 = data[data["age"]>60]

#Display the records
print(age_above_60)

      age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
2      70    1   0       145   174    0        1      125      1      2.6
3      61    1   0       148   203    0        1      161      0      0.0
4      62    0   0       138   294    1        1      106      0      1.9
10     71    0   0       112   149    0        1      125      0      1.6
21     67    0   0       106   223    0        1      142      0      0.3
...   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...
989    71    0   1       160   302    0        1      162      0      0.4
999    67    1   0       125   254    1        1      163      0      0.2
1000   64    1   0       145   212    0        0      132      0      2.0
1002   66    1   0       112   212    0        0      132      1      0.1
1016   65    1   3       138   282    1        0      174      0      1.4

      slope  ca  thal  target
2         0   0     3       0
3         2   1     3       0
4         1   3     2       0
10        1   0     2       1
21        2   2     2       1
...     ...  ..   ...     ...
989       2   2     2       1
999       1   2     3       0
1000      1   2     1       0
1002      2   1     2       0
1016      1   1     2       0

[272 rows x 14 columns]

In [17]:
print("len(age_above_60)")

len(age_above_60)

In [18]:
data.isna()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1021,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1022,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1023,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1024,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [19]:
data.isna().any()

age         False
sex         False
cp          False
trestbps    False
chol        False
fbs         False
restecg     False
thalach     False
exang       False
oldpeak     False
slope       False
ca          False
thal        False
target      False
dtype: bool

In [20]:
data.isna().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64